channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=23.3.2
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.0.0
  - numpy==1.26.2
  - pandas==2.1.3
  - psutil==5.9.7
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - typing==3.7.4.3
name: mlflow-env
